import type { Metadata } from 'next';
import { RevealOnScroll, RevealStagger } from '@/components/reveal';

export const metadata: Metadata = {
  title: 'Methodology',
  description:
    'How the Derby/1M Monte Carlo works: data sources, Beyer figures, pace/track/post adjustments, limitations.',
};

export default function MethodologyPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-12 md:px-10 md:py-20">
      <header className="mb-12 border-b border-bone-200/[0.08] pb-8">
        <RevealStagger stagger={0.1}>
          <span className="eyebrow block">Derby/1M · Methodology</span>
          <h1 className="mt-4 font-display text-5xl italic leading-[1.05] text-bone-100 md:text-6xl">
            Show your work.
          </h1>
          <p className="mt-5 text-[15px] leading-relaxed text-bone-400">
            Horse-racing models are easy to make, easy to present as
            authoritative, and easy to fool. The entire point of this page is so
            you can read exactly what the model does, what it doesn&apos;t do, and
            decide for yourself whether any of it is worth listening to.
          </p>
        </RevealStagger>
      </header>

      <Section title="Data">
        <p>
          The input is a single JSON file — <Code>data/field.json</Code> — with
          the 20 Kentucky Derby starters and their stats. The file is
          regenerated by <Code>scripts/scrape_field.py</Code>, which pulls past
          performances from <a href="https://www.equibase.com/">Equibase</a>{' '}
          and falls back to{' '}
          <a href="https://www.horseracingnation.com/">Horse Racing Nation</a>{' '}
          when the primary source 403s. Horses that can&apos;t be scraped get
          flagged for manual entry — the sim refuses to run on zeros.
        </p>
        <p>
          Per horse, we carry the last three Beyer Speed Figures, running
          style, distance aptitude, class rating, dirt aptitude, wet-track
          aptitude (or <em>null</em> if unknown), and post position.
        </p>
      </Section>

      <Section title="What is a Beyer figure">
        <p>
          A Beyer Speed Figure is a speed-adjusted rating of a horse&apos;s
          performance in a single race, calibrated so a 100 is
          &ldquo;competitive on any track.&rdquo; Horses who&apos;ll contest
          the Derby typically come in averaging 95–105 in their final prep.
          The model treats the last-3 Beyer figures as draws from each
          horse&apos;s latent ability distribution — the mean anchors
          &ldquo;how fast,&rdquo; the spread anchors &ldquo;how consistent.&rdquo;
        </p>
      </Section>

      <Section title="Running styles">
        <p>
          <Code>E</Code> (&ldquo;early&rdquo;) horses want the lead;{' '}
          <Code>E/P</Code> press the pace;
          <Code>P</Code> sit just off it; <Code>S</Code> close from behind.
          We read style from the horse&apos;s early-pace figure relative to
          the field in prior races. Style determines how a horse reacts to
          the pace scenario:
        </p>
        <table className="my-4 w-full border-collapse font-mono text-[12px]">
          <thead className="text-bone-500">
            <tr className="border-b border-bone-200/[0.08]">
              <th className="py-2 text-left">Pace</th>
              <th className="py-2 text-right">E</th>
              <th className="py-2 text-right">E/P</th>
              <th className="py-2 text-right">P</th>
              <th className="py-2 text-right">S</th>
            </tr>
          </thead>
          <tbody className="tabular-nums">
            <tr className="border-b border-bone-200/[0.05]">
              <td className="py-2 text-bone-300">Fast early</td>
              <td className="py-2 text-right">−4.0</td>
              <td className="py-2 text-right">−2.0</td>
              <td className="py-2 text-right">+1.5</td>
              <td className="py-2 text-right">+3.5</td>
            </tr>
            <tr className="border-b border-bone-200/[0.05]">
              <td className="py-2 text-bone-300">Honest</td>
              <td className="py-2 text-right">0</td>
              <td className="py-2 text-right">0</td>
              <td className="py-2 text-right">0</td>
              <td className="py-2 text-right">0</td>
            </tr>
            <tr>
              <td className="py-2 text-bone-300">Slow early</td>
              <td className="py-2 text-right">+3.0</td>
              <td className="py-2 text-right">+1.5</td>
              <td className="py-2 text-right">−1.0</td>
              <td className="py-2 text-right">−3.0</td>
            </tr>
          </tbody>
        </table>
        <p>
          Units are Beyer points. The magnitudes are calibrated from
          pace-profile studies of graded dirt routes 1950–2023, which show
          fast early fractions shift individual performances ~3–6 points.
        </p>
      </Section>

      <Section title="Track condition">
        <p>
          Wet tracks separate. A horse with known wet-track aptitude (scaled
          0–1) gets a shift of up to ±8 Beyer points on a sloppy surface,
          ±7 on muddy, ±2 on good, and zero on fast. For horses with{' '}
          <em>no</em> wet-track experience, we draw their wet aptitude each
          iteration from a field-wide prior — <Code>N(0.5, 0.25)</Code>{' '}
          clipped to [0, 1] — so the uncertainty shows up as spread, not a
          point estimate.
        </p>
      </Section>

      <Section title="Post position">
        <p>
          From 1950–2023 Derby results, posts 1–2 (rail, compromised trip)
          and 17–20 (stuck wide) have won materially less than their
          field-share would predict. The model applies a small additive
          penalty: −1.8 at post 1, tapering to zero in the middle, and
          ramping back to −2.4 at post 20. Middle posts (3–16) carry no
          penalty.
        </p>
      </Section>

      <Section title="Beliefs">
        <p>
          The <Code>±</Code> next to each horse lets you add a personal
          adjustment in Beyer points. Some use cases: the horse just lost
          their regular rider, the trainer just hinted at an injury, the
          workout reports are glowing. A <Code>+3</Code> raises the horse&apos;s
          mean three points. Use it; the sim was designed to invite
          skeptical intervention.
        </p>
      </Section>

      <Section title="The Monte Carlo">
        <p>
          For each of 1,000,000 iterations we draw every horse&apos;s &ldquo;true
          speed today&rdquo; from a Normal distribution centered at their
          modifier-adjusted mean, with standard deviation derived from the
          spread of their last three Beyers (floored at 4 points so no horse
          is modeled as deterministic). The horse with the highest draw
          wins; <Code>argsort</Code> gives us the full finish order.
        </p>
        <p>
          From the 1M finish-order matrix we read each horse&apos;s P(win),
          P(top-3), P(top-4), mean finish position, and their finish
          histogram — that&apos;s what the viz draws. The whole pipeline is
          NumPy-vectorized over arrays of shape <Code>(1M, 20)</Code>; there
          are no Python loops over horses or iterations. On commodity
          hardware it completes well under 10 seconds.
        </p>
      </Section>

      <Section title="Sanity check">
        <p>
          Before the site ships, <Code>scripts/sanity_check.py</Code>{' '}
          compares the model&apos;s P(win) distribution to the published
          morning-line odds. Any horse where the disagreement exceeds 12
          percentage points, or where the model says &lt;1% while the line
          is ≥5%, gets flagged. That table gets read before a deploy.
        </p>
      </Section>

      <Section title="What the model doesn’t do">
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Jockey changes.</strong> A last-minute switch from a
            journeyman to a Hall-of-Famer does not move our estimates.
          </li>
          <li>
            <strong>Workout reports.</strong> Bullet works are not ingested.
            Use the belief slider to encode your read.
          </li>
          <li>
            <strong>Traffic / trip.</strong> Derby fields are 20-horse
            scrambles; clean trips are stochastic in ways this model
            doesn&apos;t simulate explicitly.
          </li>
          <li>
            <strong>Scratch re-draws.</strong> If a horse scratches race-day,
            <Code>data/field.json</Code> must be edited by hand before the
            sim runs cleanly.
          </li>
          <li>
            <strong>Morning-line odds.</strong> We show them for reference;
            the model doesn&apos;t &ldquo;pull toward&rdquo; the market.
          </li>
        </ul>
      </Section>

      <Section title="Repo">
        <p>
          Open source.{' '}
          <a
            className="text-rose-glow underline underline-offset-4"
            href="https://github.com/"
          >
            github.com/…/derby1m
          </a>
          . PRs welcome; issues welcome; the calibration constants in{' '}
          <Code>api/simulate.py</Code> are deliberately exposed so you can
          fork and argue with them.
        </p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <RevealOnScroll>
      <section className="mb-12">
        <h2 className="mb-4 font-display text-3xl italic leading-tight text-bone-100">
          {title}
        </h2>
        <div className="flex flex-col gap-4 text-[15px] leading-relaxed text-bone-300">
          {children}
        </div>
      </section>
    </RevealOnScroll>
  );
}

function Code({ children }: { children: React.ReactNode }) {
  return (
    <code className="rounded-sm bg-ink-800 px-1.5 py-0.5 font-mono text-[12px] text-bone-200">
      {children}
    </code>
  );
}
