import type { Metadata } from 'next';
import { RevealOnScroll, RevealStagger } from '@/components/reveal';
import {
  DistroSparkle,
  IterationDiagram,
  PacePosition,
  RoseRule,
  TrackOval,
} from '@/components/graphics';

export const metadata: Metadata = {
  title: 'Methodology',
  description:
    'How the Derby/1M Monte Carlo works: data sources, Beyer figures, pace, track, post position, limitations, and the post-race scorecard.',
};

// Approximate historical win-rate weights for posts 1..20, relative to expected
// share. Sourced from compilations of 1986–2023 Derby finishes (post 17 has
// won zero times in that window; posts 5–10 have won most often).
const POST_WEIGHTS = [
  0.18, 0.30, 0.55, 0.72, 0.90, 0.95, 0.88, 0.82, 0.78, 0.85,
  0.62, 0.58, 0.55, 0.50, 0.45, 0.40, 0.10, 0.20, 0.25, 0.30,
];

export default function MethodologyPage() {
  return (
    <article className="mx-auto max-w-[760px] px-5 py-12 md:px-8 md:py-20">
      <header className="mb-14 border-b border-paper-200 pb-10">
        <RevealStagger stagger={0.1}>
          <span className="eyebrow block">Derby/1M · Methodology</span>
          <h1 className="mt-4 font-display text-[44px] italic leading-[1.05] text-ink-900 md:text-[64px]">
            Show your work.
          </h1>
          <p className="mt-5 text-[17px] leading-relaxed text-ink-700">
            Horse-racing models are easy to make, easy to present as
            authoritative, and easy to fool. The entire point of this page is
            so you can read exactly what the model does, what it doesn&apos;t
            do, and decide for yourself whether any of it is worth listening
            to. The <Code>api/simulate.py</Code> file in the repo is the
            actual source of truth — every constant referenced below is named
            in that file, with the same value, in the open. If you disagree
            with a number, fork the repo and change it.
          </p>
        </RevealStagger>
      </header>

      <Section title="1 · Overview">
        <p>
          Derby/1M is a Monte Carlo simulator for the 152nd Kentucky Derby.
          It builds a small probabilistic model of each starter&apos;s
          ability, samples one million simulated races over the full
          twenty-horse field, and reports the resulting distribution of
          finish positions for every horse. The headline number for each
          horse is its <em>P(win)</em>: the share of simulated races in
          which that horse&apos;s sampled performance was the highest. The
          fuller answer — visible in the bar on the home page — is the
          horse&apos;s entire finish histogram, position by position{' '}
          <DistroSparkle width={120} />.
        </p>
        <p>
          The model is not in the business of telling you what to bet on.
          It does not accept money, it does not connect to a sportsbook,
          and it deliberately stays away from anything that would push it
          toward the morning line. It is an attempt to publish a numerate
          opinion about a famously chaotic race, expose every assumption,
          and then publish a post-race scorecard the morning after Derby
          Day so the whole exercise can be graded.
        </p>
      </Section>

      <Section title="2 · Data sources">
        <p>
          The input is a single JSON file — <Code>data/field.json</Code>{' '}
          — containing the twenty Kentucky Derby starters and their stats.
          The file is regenerated by{' '}
          <Code>scripts/scrape_field.py</Code>, which pulls past
          performances from{' '}
          <a className="link" href="https://www.equibase.com/">
            Equibase
          </a>{' '}
          and falls back to{' '}
          <a className="link" href="https://www.horseracingnation.com/">
            Horse Racing Nation
          </a>{' '}
          when the primary source returns 403. Horses whose past
          performances cannot be scraped get flagged for manual entry; the
          simulator refuses to run if any horse is left with all-zero
          features.
        </p>
        <p>
          Until the post draw on April 25, the morning-line column is
          marked <em>(projected)</em>: the official line for the 2026
          Derby is not released until the field is finalized, so any
          number shown before then is sourced from the early lines posted
          by Mike Battaglia, Tom Tammaro, or DRF&apos;s pre-draw projections.
          After post-draw, <Code>data/field.json</Code> is regenerated and
          the projected flag clears. The data&apos;s last-modified
          timestamp is shown in the site footer; if it lags Derby Day, you
          should be skeptical.
        </p>
      </Section>

      <Section title="3 · The horse model">
        <p>
          Every horse is reduced to a small handful of numbers. This is
          the entire feature vector the simulator sees, and it is why the
          model is best understood as a sketch rather than an oracle.
        </p>
        <ul className="my-4 flex flex-col gap-2">
          <Bullet term="beyer_last_3">
            The horse&apos;s three most-recent Beyer Speed Figures. The
            mean anchors how fast the horse usually runs; the
            sample-standard-deviation anchors how consistent the horse is
            from race to race. We floor the per-horse standard deviation
            at five points so a horse with three identical figures
            doesn&apos;t become deterministic in the sim.
          </Bullet>
          <Bullet term="running_style">
            One of <Code>E</Code>, <Code>E/P</Code>, <Code>P</Code>,{' '}
            <Code>S</Code> — see the next section. Determines how the
            horse responds to the user-selected pace scenario.
          </Bullet>
          <Bullet term="distance_aptitude">
            Scalar in [0,1]. A 0.5 is &ldquo;average for a route horse,&rdquo;
            1.0 is &ldquo;has clearly proven they handle ten furlongs.&rdquo; This
            scales an additive ±1.75-point shift around the horse&apos;s mean.
          </Bullet>
          <Bullet term="class_rating">
            Scalar in [0,10]. Captures the strength of competition the
            horse has faced and beaten. A 5 is neutral. Each unit moves
            the horse&apos;s mean by 0.25 Beyer points.
          </Bullet>
          <Bullet term="surface_aptitude_dirt">
            Scalar in [0,1]. The Derby is on dirt; horses who have been
            campaigned on synthetics get penalized here.
          </Bullet>
          <Bullet term="surface_aptitude_wet">
            Scalar in [0,1] <em>or</em> <Code>null</Code>. A horse with no
            wet-track experience gets a per-iteration draw from a
            field-wide prior — see the track-condition section. Encoding
            the unknown explicitly is the point.
          </Bullet>
          <Bullet term="post_position">
            Integer in [1,20]. Determines the horse&apos;s additive
            post-position penalty.
          </Bullet>
        </ul>
        <p>
          That is the whole horse. There is no jockey term, no trainer
          term, no breeding sire-line, no workout time. Adding any of
          those would require a defensible mechanism to estimate them —
          and most of them are dominated, in 20-horse Derby fields, by
          the noise the model already explicitly captures.
        </p>
      </Section>

      <Section title="4 · Running-style taxonomy">
        <p>
          A horse&apos;s running style is read from its early-pace figure
          relative to the field across its prior races. The four buckets
          are deliberately coarse — fine-grained styles disagree between
          handicappers and don&apos;t pay off in cleaner predictions.
        </p>
        <div className="my-5 grid grid-cols-2 gap-x-6 gap-y-4 md:grid-cols-4">
          <StyleCell style="E" name="Early" hint="Wants the lead from the gate" />
          <StyleCell style="E/P" name="Press" hint="Stays within a length of the leader" />
          <StyleCell style="P" name="Stalk" hint="Sits 3–5 lengths off the pace" />
          <StyleCell style="S" name="Closer" hint="Runs from the back of the pack" />
        </div>
        <p>
          The four styles are scored against three pace scenarios — slow,
          honest, and fast — to produce the additive Beyer shift in the
          table below. Magnitudes are calibrated from a survey of pace
          studies on graded dirt routes between 1950 and 2023, which
          consistently find that pace shape moves individual performances
          on the order of three to six Beyer points when fractions are
          unusually fast or slow.
        </p>
        <table className="my-6 w-full border-collapse font-mono text-[12px]">
          <thead>
            <tr className="border-b border-paper-300 text-ink-500">
              <th className="py-2 text-left font-medium">Pace</th>
              <th className="py-2 text-right font-medium">E</th>
              <th className="py-2 text-right font-medium">E/P</th>
              <th className="py-2 text-right font-medium">P</th>
              <th className="py-2 text-right font-medium">S</th>
            </tr>
          </thead>
          <tbody className="tabular-nums text-ink-800">
            <tr className="border-b border-paper-200">
              <td className="py-2.5 text-ink-700">Fast early</td>
              <td className="py-2.5 text-right text-signal-red">−4.0</td>
              <td className="py-2.5 text-right text-signal-red">−2.0</td>
              <td className="py-2.5 text-right text-signal-green">+1.5</td>
              <td className="py-2.5 text-right text-signal-green">+3.5</td>
            </tr>
            <tr className="border-b border-paper-200">
              <td className="py-2.5 text-ink-700">Honest</td>
              <td className="py-2.5 text-right text-ink-500">0</td>
              <td className="py-2.5 text-right text-ink-500">0</td>
              <td className="py-2.5 text-right text-ink-500">0</td>
              <td className="py-2.5 text-right text-ink-500">0</td>
            </tr>
            <tr>
              <td className="py-2.5 text-ink-700">Slow early</td>
              <td className="py-2.5 text-right text-signal-green">+3.0</td>
              <td className="py-2.5 text-right text-signal-green">+1.5</td>
              <td className="py-2.5 text-right text-signal-red">−1.0</td>
              <td className="py-2.5 text-right text-signal-red">−3.0</td>
            </tr>
          </tbody>
        </table>
        <p>
          The shift is added directly to the horse&apos;s mean before the
          Normal sample is drawn. A four-point downshift on a deep closer
          in a slow-pace scenario is a meaningful headwind, but it is not
          deterministic — a horse who reliably breaks 100 will still post
          a 100 in some iterations even with the penalty applied, because
          the per-horse standard deviation absorbs most of the action.
        </p>
      </Section>

      <Section title="5 · The simulation, one iteration at a time">
        <p>
          One simulated race works like this. For each horse we compute an{' '}
          <em>effective mean</em> equal to the horse&apos;s base Beyer
          mean plus the static aptitude shifts (class, distance, dirt),
          plus the pace shift for the selected scenario, plus the
          post-position penalty, plus any user-supplied belief override.
          We then draw one sample from a Normal distribution centered at
          that effective mean with standard deviation equal to the
          horse&apos;s last-three Beyer spread (floored at five points).
          The horse with the highest sample wins. <Code>argsort</Code>{' '}
          ranks the rest, producing a complete finish order from first to
          twentieth. That is one iteration. The picture below is a
          five-horse cartoon of exactly that step:
        </p>
        <figure className="my-6 rounded-sm border border-paper-200 bg-paper-100 p-5">
          <IterationDiagram />
          <figcaption className="mt-3 font-mono text-[11px] uppercase tracking-[0.14em] text-ink-500">
            One iteration · five horses · the rightmost draw wins
          </figcaption>
        </figure>
        <p>
          We repeat this one million times. The draws and rankings are
          done in NumPy as a single vectorized operation over an{' '}
          <Code>(1 000 000, n)</Code> matrix, which is why the whole
          simulation completes in under half a second on the deployed
          API. From the matrix of finish orders we count, for each horse,
          how often they finished in each of the twenty positions. That
          per-horse count divided by one million is the horse&apos;s
          finish histogram. The first column is P(win); the first three
          summed is P(top-3); the first four summed is P(top-4); the
          inner product with [1, 2, 3, …, 20] is the horse&apos;s mean
          finish position. Those are the numbers shown next to each
          horse&apos;s row in the chart.
        </p>
      </Section>

      <Section title="6 · Track-condition adjustments">
        <p>
          A wet track is the largest source of regime change in the
          model. Horses with a known wet-track aptitude (a scalar in
          [0,1] from past performances on off tracks) get an additive
          shift of up to plus or minus eight Beyer points on a sloppy
          surface, plus or minus seven on muddy, plus or minus two on
          good, and zero on fast. The maximum shift is reached at the
          extremes of the aptitude scale; a horse rated 0.5 — perfectly
          neutral — gets no shift even on the wettest surface.
        </p>
        <p>
          For horses with <em>no</em> wet-track sample at all, we don&apos;t
          guess. Each iteration draws their wet aptitude fresh from a
          field-wide prior:{' '}
          <Code>N(0.5, 0.25)</Code> clipped to the unit interval. The
          consequence is that an unknown horse on a sloppy track sees its
          own mean wander by several Beyer points from one iteration to
          the next — exactly the kind of fat-tailed uncertainty that
          should manifest as a wider finish histogram, not a confident
          point estimate. Encoding the unknown as variance is the entire
          point.
        </p>
      </Section>

      <Section title="7 · Post position">
        <p>
          Modern Kentucky Derby fields are twenty horses on a track
          chute that was designed for fourteen. The rail and the far
          outside both pay a measurable price. From 1986 — the year
          the field expanded to twenty — through 2023, posts one and
          two have won the Derby roughly half as often as a uniform
          distribution would predict, and posts seventeen through
          twenty have won roughly one-fifth as often. Post seventeen
          has not won the race in that window at all. The model
          encodes the asymmetry as a small additive penalty:
        </p>
        <figure className="my-6 rounded-sm border border-paper-200 bg-paper-100 p-5">
          <TrackOval weights={POST_WEIGHTS} />
          <figcaption className="mt-3 font-mono text-[11px] uppercase tracking-[0.14em] text-ink-500">
            Schematic Derby chute · gates 1–20 · shaded by relative historical win rate (1986–2023)
          </figcaption>
        </figure>
        <p>
          The penalties applied in the model:{' '}
          <Code>−1.8</Code> at post 1, <Code>−1.0</Code> at post 2, zero
          for posts 3 through 16, and a ramp from <Code>−1.2</Code> at
          post 17 down to <Code>−2.4</Code> at post 20. The size of the
          penalty is small for two reasons. First, post-position effects
          are real but the sample is thin — fewer than forty modern
          Derbies. Second, in a 20-horse race the dominant uncertainty is
          the pace scramble itself, not the gate the horse broke from.
          The penalty exists to nudge the model toward what history
          actually shows; it is not a thesis.
        </p>
      </Section>

      <Section title="8 · Beliefs (the manual override)">
        <p>
          Next to each horse&apos;s row sits a <Code>±</Code> stepper.
          Adding <Code>+3</Code> raises that horse&apos;s mean by three
          Beyer points before sampling; subtracting <Code>−2</Code> drops
          it by two. Beliefs are intentionally additive, transparent, and
          capped at <Code>±10</Code>. They exist because public data
          inevitably misses things: a workout report that turned heads at
          dawn, a jockey switch announced an hour ago, a stable-area
          rumour about a sore foot. Encode it, run the sim, see how the
          probability surface changes. The simulator was designed to
          invite skeptical intervention, not to defend a single answer.
        </p>
        <p>
          The reset button beside the scenario panel zeros every belief
          in one click. There is no persistent state — refresh the page
          and the model is back to its baseline.
        </p>
      </Section>

      <Section title="9 · Sanity checks before deploy">
        <p>
          Before any field gets shipped to production,{' '}
          <Code>scripts/sanity_check.py</Code> runs the full simulation
          against the projected morning line. Any horse where the
          model&apos;s P(win) disagrees with the morning line by more
          than twelve percentage points, or where the model says less
          than one percent while the line is at five percent or higher,
          gets flagged. The flagged table is read manually before merge.
          Big disagreements are fine — the model is not the line — but
          they had better come from a Beyer or pace argument we can
          point to.
        </p>
        <p>
          A second script, <Code>scripts/test_sim.py</Code>, asserts the
          probabilistic invariants you would want from any honest Monte
          Carlo: the P(win) values sum to one within numerical tolerance,
          no horse&apos;s histogram contains negative entries, the
          ranking under a fixed seed is bit-identical across runs, and
          the response shape matches the TypeScript types the frontend
          expects. The continuous-integration step runs both before any
          push.
        </p>
      </Section>

      <Section title="10 · What the model does not do">
        <p>
          Honest limits, in roughly the order they would matter on Derby
          Day:
        </p>
        <ul className="my-4 flex flex-col gap-3">
          <Bullet term="Jockeys">
            A last-minute switch from a journeyman to a Hall-of-Famer
            does not move the model. The literature is split on whether
            jockey effects are large enough to estimate cleanly in twenty-horse
            fields; until there is a clear win, the field stays empty.
          </Bullet>
          <Bullet term="Trainer form">
            The model carries no trainer term. A barn that has gone cold
            in April is treated identically to one whose stakes runners
            are firing at fifty percent.
          </Bullet>
          <Bullet term="Workouts">
            Bullet works in the days before the race are not ingested.
            Use the belief slider to encode the read.
          </Bullet>
          <Bullet term="Trip and traffic">
            Twenty-horse fields are scrambles. Whether a horse gets a
            clean trip is itself substantially stochastic; the model
            does not simulate trip explicitly. Some of that noise is
            absorbed into the per-horse Beyer standard deviation.
          </Bullet>
          <Bullet term="Day-of weather and rail bias">
            The track-condition selector is a discrete switch — fast,
            good, sloppy, muddy — not a real-time read on race-day
            conditions or which part of the strip has been favored.
          </Bullet>
          <Bullet term="Sire-line and pedigree">
            Beyond the dirt-aptitude scalar, the model knows nothing
            about sire-line stamina or the produce records of distance
            broodmare sires. There is real signal there; capturing it
            cleanly requires a defensible feature, not a heuristic.
          </Bullet>
          <Bullet term="Scratches">
            If a horse scratches in the morning,{' '}
            <Code>data/field.json</Code> must be edited by hand and the
            sim re-run. The model is not live-stitched.
          </Bullet>
          <Bullet term="The morning line">
            We display it next to each horse for reference. The model
            does not pull toward it. That is on purpose — when the model
            disagrees with the line, the disagreement is the whole point
            of looking at the model.
          </Bullet>
        </ul>
      </Section>

      <Section title="11 · The scorecard commitment">
        <p>
          On the morning of May 3, the scorecard at{' '}
          <a className="link" href="/scorecard">
            /scorecard
          </a>{' '}
          will publish the model&apos;s pre-race probability surface next
          to the actual finish order, the Brier score and log-loss for
          the model and for the morning line, a flagged list of horses
          where the model and the line disagreed by more than twelve
          percentage points (with which side won), and a short
          plain-English writeup of what the model got right and where it
          missed. The Brier and log-loss numbers are not negotiable; the
          writeup is. If the model loses to the morning line, the
          scorecard says so plainly.
        </p>
      </Section>

      <RoseRule className="my-12" />

      <Section title="Repo and disclaimer">
        <p>
          The source is open at{' '}
          <a className="link" href="https://github.com/sharziki/derby1m">
            github.com/sharziki/derby1m
          </a>
          . PRs and issues welcome. The calibration constants in{' '}
          <Code>api/simulate.py</Code> are deliberately exposed and
          documented in this page so anyone can fork the project and
          argue with them.
        </p>
        <p className="text-[14px] leading-relaxed text-ink-600">
          Derby/1M is a research and entertainment project. It is not a
          tipping service, it does not accept wagers, and it is not
          affiliated with Churchill Downs Incorporated, the Kentucky
          Derby, or any racing or wagering operator. All horse names,
          jockey names, trainer names, and morning-line numbers shown
          before the official post draw are projections from publicly
          available sources and are clearly labeled as such.
        </p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <RevealOnScroll>
      <section className="mb-14">
        <h2 className="mb-4 font-display text-[28px] italic leading-tight text-ink-900 md:text-[34px]">
          {title}
        </h2>
        <div className="flex flex-col gap-4 text-[16px] leading-[1.7] text-ink-800 md:text-[17px]">
          {children}
        </div>
      </section>
    </RevealOnScroll>
  );
}

function StyleCell({ style, name, hint }: { style: 'E' | 'E/P' | 'P' | 'S'; name: string; hint: string }) {
  return (
    <div className="flex flex-col gap-2 border-l-2 border-paper-200 pl-3">
      <div className="flex items-center gap-3">
        <span className="font-mono text-[12px] font-medium text-rose-deep">{style}</span>
        <span className="font-display text-[18px] italic text-ink-900">{name}</span>
      </div>
      <PacePosition style={style} />
      <span className="text-[13px] leading-snug text-ink-600">{hint}</span>
    </div>
  );
}

function Bullet({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <li className="flex flex-col gap-1 border-l-2 border-paper-200 pl-3">
      <span className="font-mono text-[12px] uppercase tracking-[0.10em] text-rose-deep">
        {term}
      </span>
      <span className="text-[15px] leading-[1.65] text-ink-800">{children}</span>
    </li>
  );
}

function Code({ children }: { children: React.ReactNode }) {
  return (
    <code className="rounded-sm bg-paper-200 px-1.5 py-0.5 font-mono text-[12px] text-ink-800">
      {children}
    </code>
  );
}
